config/routes.rb
BarkantineParents::Application.routes.draw do

  resources :resources_and_links

  resources :birth_stories

  resources :news

  root :to => 'pages#index'

end

app/models/birth_story.rb
class BirthStory < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/resources_and_link.rb
class ResourcesAndLink < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/birth_stories_controller.rb
class BirthStoriesController < ApplicationController
  # GET /birth_stories
  # GET /birth_stories.json
  def index
    @birth_stories = BirthStory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @birth_stories }
    end
  end

  # GET /birth_stories/1
  # GET /birth_stories/1.json
  def show
    @birth_story = BirthStory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @birth_story }
    end
  end

  # GET /birth_stories/new
  # GET /birth_stories/new.json
  def new
    @birth_story = BirthStory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @birth_story }
    end
  end

  # GET /birth_stories/1/edit
  def edit
    @birth_story = BirthStory.find(params[:id])
  end

  # POST /birth_stories
  # POST /birth_stories.json
  def create
    @birth_story = BirthStory.new(params[:birth_story])

    respond_to do |format|
      if @birth_story.save
        format.html { redirect_to @birth_story, notice: 'Birth story was successfully created.' }
        format.json { render json: @birth_story, status: :created, location: @birth_story }
      else
        format.html { render action: "new" }
        format.json { render json: @birth_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /birth_stories/1
  # PUT /birth_stories/1.json
  def update
    @birth_story = BirthStory.find(params[:id])

    respond_to do |format|
      if @birth_story.update_attributes(params[:birth_story])
        format.html { redirect_to @birth_story, notice: 'Birth story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @birth_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birth_stories/1
  # DELETE /birth_stories/1.json
  def destroy
    @birth_story = BirthStory.find(params[:id])
    @birth_story.destroy

    respond_to do |format|
      format.html { redirect_to birth_stories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index 
 	@news = News.first
 	@birth_stories = BirthStory.first
 	@resources_and_links = ResourcesAndLink.first
  end
end

app/controllers/resources_and_links_controller.rb
class ResourcesAndLinksController < ApplicationController
  # GET /resources_and_links
  # GET /resources_and_links.json
  def index
    @resources_and_links = ResourcesAndLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resources_and_links }
    end
  end

  # GET /resources_and_links/1
  # GET /resources_and_links/1.json
  def show
    @resources_and_link = ResourcesAndLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resources_and_link }
    end
  end

  # GET /resources_and_links/new
  # GET /resources_and_links/new.json
  def new
    @resources_and_link = ResourcesAndLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resources_and_link }
    end
  end

  # GET /resources_and_links/1/edit
  def edit
    @resources_and_link = ResourcesAndLink.find(params[:id])
  end

  # POST /resources_and_links
  # POST /resources_and_links.json
  def create
    @resources_and_link = ResourcesAndLink.new(params[:resources_and_link])

    respond_to do |format|
      if @resources_and_link.save
        format.html { redirect_to @resources_and_link, notice: 'Resources and link was successfully created.' }
        format.json { render json: @resources_and_link, status: :created, location: @resources_and_link }
      else
        format.html { render action: "new" }
        format.json { render json: @resources_and_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resources_and_links/1
  # PUT /resources_and_links/1.json
  def update
    @resources_and_link = ResourcesAndLink.find(params[:id])

    respond_to do |format|
      if @resources_and_link.update_attributes(params[:resources_and_link])
        format.html { redirect_to @resources_and_link, notice: 'Resources and link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resources_and_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources_and_links/1
  # DELETE /resources_and_links/1.json
  def destroy
    @resources_and_link = ResourcesAndLink.find(params[:id])
    @resources_and_link.destroy

    respond_to do |format|
      format.html { redirect_to resources_and_links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birth_stories_helper.rb
module BirthStoriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resources_and_links_helper.rb
module ResourcesAndLinksHelper
end

app/views/birth_stories/_form.html.erb
<%= form_for(@birth_story) do |f| %>
  <% if @birth_story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@birth_story.errors.count, "error") %> prohibited this birth_story from being saved:</h2>

      <ul>
      <% @birth_story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birth_stories/edit.html.erb
<h1>Editing birth_story</h1>

<%= render 'form' %>

<%= link_to 'Show', @birth_story %> |
<%= link_to 'Back', birth_stories_path %>

app/views/birth_stories/index.html.erb
<h1>Listing birth_stories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @birth_stories.each do |birth_story| %>
  <tr>
    <td><%= birth_story.title %></td>
    <td><%= birth_story.content %></td>
    <td><%= link_to 'Show', birth_story %></td>
    <td><%= link_to 'Edit', edit_birth_story_path(birth_story) %></td>
    <td><%= link_to 'Destroy', birth_story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Birth story', new_birth_story_path %>

app/views/birth_stories/new.html.erb
<h1>New birth_story</h1>

<%= render 'form' %>

<%= link_to 'Back', birth_stories_path %>

app/views/birth_stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @birth_story.title %>
</p>

<p>
  <b>Content:</b>
  <%= @birth_story.content %>
</p>


<%= link_to 'Edit', edit_birth_story_path(@birth_story) %> |
<%= link_to 'Back', birth_stories_path %>

app/views/layouts/application.html.erb
<head>
  <title>BarkantineParents</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <style>
  	h2 {font size: 48px;
  	}
  </style>
</head>

<body>



<%= yield %>


</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.title %></td>
    <td><%= news.content %></td>
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news.title %>
</p>

<p>
  <b>Content:</b>
  <%= @news.content %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/pages/index.html.erb
	<div> <!-- style="background-color:silver;border:10px silver solid"> -->
		<h1>Barkantine Parents</h1>

		<p>Welcome to the Barkantine Parents' Group the support group for parents and parents-to-be using the Barkantine Birth Centre</p>
	</div>	    

<div class="container_12">

	<div class="content-box grid_2"> <!-- style="background-color:white;height:500px;width:16%;float:left;border:10px silver solid"> -->
		<h3>  
			About us 
		</h3>
		<p> We are a friendly, volunteer run support group for parents and parents-to-be using or hoping to use the Barkantine Birth Centre to share information, tips and stories.  
		 <br> 
		 <br> 
		 <b> 
		 	We meet on the last Saturday of each month 
		</b> 
			at the Barkantine between 10am and 1pm.  
		</p>
	</div>	

	<div class="content-box grid_3">
	<%= image_tag "IMG_0499.JPG" %>
		<h3>
	  		<b>
			<%= @news.title %> 
			</b>	
		</h3>
		<p>
			<br>
			<%= @news.content %>
		</p>
	</div>	

	<div class="content-box grid_3">
		<h3>
			<b>
			<%= @resources_and_links.title %>
			</b>
		</h3>
		<p>
			<br>
			<%= @resources_and_links.content %>
		</p>
		<%= link_to "Go to resources and links", resources_and_links_path %>
	</div>	

	<div class="content-box grid_3">
    	<h3>
			<b>
			<%= @birth_stories.title %>
			</b>
		</h3>
		<p>
			<br>
			<%= @birth_stories.content %>
		</p>
		<%= link_to "Go to birth stories", birth_stories_path %>
	</div>	

</div>

app/views/resources_and_links/_form.html.erb
<%= form_for(@resources_and_link) do |f| %>
  <% if @resources_and_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resources_and_link.errors.count, "error") %> prohibited this resources_and_link from being saved:</h2>

      <ul>
      <% @resources_and_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources_and_links/edit.html.erb
<h1>Editing resources_and_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @resources_and_link %> |
<%= link_to 'Back', resources_and_links_path %>

app/views/resources_and_links/index.html.erb
<h1>Listing resources_and_links</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources_and_links.each do |resources_and_link| %>
  <tr>
    <td><%= resources_and_link.title %></td>
    <td><%= resources_and_link.content %></td>
    <td><%= link_to 'Show', resources_and_link %></td>
    <td><%= link_to 'Edit', edit_resources_and_link_path(resources_and_link) %></td>
    <td><%= link_to 'Destroy', resources_and_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resources and link', new_resources_and_link_path %>

app/views/resources_and_links/new.html.erb
<h1>New resources_and_link</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_and_links_path %>

app/views/resources_and_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @resources_and_link.title %>
</p>

<p>
  <b>Content:</b>
  <%= @resources_and_link.content %>
</p>


<%= link_to 'Edit', edit_resources_and_link_path(@resources_and_link) %> |
<%= link_to 'Back', resources_and_links_path %>